### ISSUE TITLE
Failed resolution of: Lcom/microsoft/device/dualscreen/layout/ScreenHelper;

### ISSUE THREAD

**Issue by PrabhatLigal** [Azure-Samples/communication-services-ui-library-xamarin#15]
## Summary:
Hi, I was testing the sample project on android tablet but it keeps crashing with the following exception. The build is successful but app crashed when composite UI is launched on Android tablet.After going through the documentation , I found out that  the dualscreen-layout aar is mentioned on README but it is missing in both project folder and download script.  Figured it might be due to missing dependency. 
https://github.com/Azure-Samples/communication-services-ui-library-xamarin/blob/main/XamarinAndroidBindings/README.md

### This issue is for a: 
- [X] bug report 
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Minimal steps to reproduce
- Build 
- Debug on Android Tablet
- Lauch Composite UI 
- Exception occur on composite UI launch

### Log
[communication.ui] com.azure.android.communication.ui.calling.redux.action.PermissionAction$AudioPermissionRequested@8378567
[AndroidRuntime] Shutting down VM
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: com.azure.communication.ui.calling.communicationcallingxamarinsampleapp, PID: 6758
[AndroidRuntime] java.lang.NoClassDefFoundError: Failed resolution of: Lcom/microsoft/device/dualscreen/layout/ScreenHelper;
[AndroidRuntime] 	at com.microsoft.fluentui.util.DuoSupportUtils.isDualScreenMode(DuoSupportUtils.kt:23)
[AndroidRuntime] 	at com.microsoft.fluentui.util.DuoSupportUtils.isWindowDoublePortrait(DuoSupportUtils.kt:39)
[AndroidRuntime] 	at com.microsoft.fluentui.snackbar.Snackbar.<init>(Snackbar.kt:143)
[AndroidRuntime] 	at com.microsoft.fluentui.snackbar.Snackbar.<init>(Snackbar.kt:36)
[AndroidRuntime] 	at com.microsoft.fluentui.snackbar.Snackbar$Companion.make(Snackbar.kt:51)
[AndroidRuntime] 	at com.azure.android.communication.ui.calling.presentation.fragment.setup.components.ErrorInfoView.initSnackBar(ErrorInfoView.kt:82)
[AndroidRuntime] 	at com.azure.android.communication.ui.calling.presentation.fragment.setup.components.ErrorInfoView.start(ErrorInfoView.kt:32)
[AndroidRuntime] 	at com.azure.android.communication.ui.calling.presentation.fragment.setup.SetupFragment.onViewCreated(SetupFragment.kt:97)
[AndroidRuntime] 	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
[AndroidRuntime] 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
[AndroidRuntime] 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
[AndroidRuntime] 	at androidx.fragment.app.FragmentController.execPendingActions(FragmentController.java:451)
[AndroidRuntime] 	at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:436)
[AndroidRuntime] 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
[AndroidRuntime] 	at android.app.Activity.performResume(Activity.java:8129)
[AndroidRuntime] 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4434)
[AndroidRuntime] 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4476)
[AndroidRuntime] 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
[AndroidRuntime] 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
[AndroidRuntime] 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
[AndroidRuntime] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:106)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:223)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:7656)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
[AndroidRuntime] Caused by: java.lang.ClassNotFoundException: Didn't find class "com.microsoft.device.dualscreen.layout.ScreenHelper" on path: DexPathList[[zip file "/data/app/~~neAmT5TEgsH06rkmeJzgRA==/com.azure.communication.ui.calling.communicationcallingxamarinsampleapp-Q-HbN2XHx6FMynLfYHyExg==/base.apk"],nativeLibraryDirectories=[/data/app/~~neAmT5TEgsH06rkmeJzgRA==/com.azure.communication.ui.calling.communicationcallingxamarinsampleapp-Q-HbN2XHx6FMynLfYHyExg==/lib/arm64, /data/app/~~neAmT5TEgsH06rkmeJzgRA==/com.azure.communication.ui.calling.communicationcallingxamarinsampleapp-Q-HbN2XHx6FMynLfYHyExg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
[AndroidRuntime] 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
[AndroidRuntime] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
[AndroidRuntime] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
[AndroidRuntime] 	... 30 more

### Expected/desired behavior
> No unhandled exceptions

### OS and Version?
> Tested on Android API 30
> Android Tablet - Nokia T20 

### Versions
> Azure Communication UI calling 1.0.0
> fluent-* 0.02

**Comment by iaulakh** [comment]
Hi @PrabhatLigal, 

would it be possible for you to try with below changes?

add below section to `CommunicationCallingXamarinSampleApp/CommunicationCallingXamarinSampleApp.Android`?
```
    <AndroidAarLibrary Include="aar\dualscreen-layout-1.0.0-alpha01.aar">
      <AndroidSkipResourceProcessing></AndroidSkipResourceProcessing>
    </AndroidAarLibrary>
```

add  attached .aar in `CommunicationCallingXamarinSampleApp/CommunicationCallingXamarinSampleApp.Android/aar`
[dualscreen-layout-1.0.0-alpha01.aar.zip](https://github.com/Azure-Samples/communication-services-ui-library-xamarin/files/9769072/dualscreen-layout-1.0.0-alpha01.aar.zip) (unzip)

**Comment by PrabhatLigal** [comment]
@iaulakh  Thanks for the dualscreen-layout-1.0.0-alpha01.aar.zip. It resolved the issue for me but it would be great if we include link for this aar on the download script as well.

**Comment by iaulakh** [comment]
Thanks for confirming @PrabhatLigal . Yes, the next step is to update script :)

**Comment by JoshuaLai** [comment]
@PrabhatLigal thank you for confirming we are going to create a defect internally to track this. We will post this git issues with updates as they come.

**Comment by iaulakh** [comment]
@PrabhatLigal would it be possible for you tor try [layouts-1.0.0-beta9.aar](https://repo1.maven.org/maven2/com/microsoft/device/dualscreen/layouts/1.0.0-beta9/layouts-1.0.0-beta9.aar) instead of `dualscreen-layout-1.0.0-alpha01.aar`? I think it should work. 
I am following with Fluent UI team to use `layouts-1.0.0-beta9.aar`.

**Comment by iaulakh** [comment]
Updated https://github.com/Azure-Samples/communication-services-ui-library-xamarin/wiki/Known-Issues. As fluent UI is removing this dependency soon, no need to include in future.
