### ISSUE TITLE
ProxyLibs Xamarin iOS 

### ISSUE THREAD

**Issue by andersonvieiragomeslopes** [Azure-Samples/communication-services-ui-library-xamarin#16]
Hello @JoshuaLai .

Continuing our conversation on the other repository...,

I have errors like this when running iOSFramework.sh script
Error: can't open iput file and no such file or directory

Do you believe that something is missing in the tutorial, some folders that must be created manually before running the script?

I have no problem with the initial steps of the tutorial

pod install

sharpie bind -sdk iphoneos -output ./ -namespace Xam.CommunicationUIProxy.iOS -scope ./CommunicationUI_Proxy.framework/Headers ./CommunicationUI_Proxy.framework/Headers/CommunicationUI_Proxy-Swift.h

My problem is in the step of generating the fat file using lipo -create, I've also tried to run the commands without using the iOSFramework.sh script but without success. It's always the same error: can't open iput file and or no such file or directory

Could you review the tutorial or see if I'm failing at any point?

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
pod install

sharpie bind -sdk iphoneos -output ./ -namespace Xam.CommunicationUIProxy.iOS -scope ./CommunicationUI_Proxy.framework/Headers ./CommunicationUI_Proxy.framework/Headers/CommunicationUI_Proxy-Swift.h

Exec iOSFramework.sh

### Any log messages given by the failure
>
1. can't open iput file and 

2. no such file or directory
3. 
### Expected/desired behavior
>
The iOSFramework.sh script should generate a folder with iOS fat files to link into the xamarin.ios project and compile.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Monterey 12.6)

### Versions
>

### Mention any other details that might be useful
Xcode 14.0

Detail, with the android project I have no problem, I can make the connections and load everything perfectly, with iOS it never worked.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by JoshuaLai** [comment]
@andersonvieiragomeslopes Just to be clear did the suggestions I gave in your other git issue (https://github.com/Laerdal/Xamarin.AzureCommunicationCalling/issues/41) work?

**Comment by andersonvieiragomeslopes** [comment]
@JoshuaLai I'm a little inexperienced on macOS :( but when I ran the command you sent me I got this output.

![image](https://user-images.githubusercontent.com/26186056/195665767-1855ba0b-b4c9-48d6-b309-c824e28e2fab.png)

**Comment by emlynmac** [comment]
@andersonvieiragomeslopes I just ran into this myself. It's due to the file already being there.
Quick fix is to make the `cp -a` command a `cp -af` command to ensure the files are overwritten.
It does look like the `lipo` command after that is executing though?

One other thing - Xcode 14 support; I needed to update Visual Studio for Mac to the latest version to make that work.

**Comment by andersonvieiragomeslopes** [comment]
> @andersonvieiragomeslopes I just ran into this myself. It's due to the file already being there. Quick fix is to make the `cp -a` command a `cp -af` command to ensure the files are overwritten. It does look like the `lipo` command after that is executing though?

Well, with that the problem changed, thanks @emlynmac 

Now I have this other problem now that I've moved on, here's a screenshot.

![image](https://user-images.githubusercontent.com/26186056/195677342-bfda7919-1c74-49f1-a485-e77f068a4a14.png)

**Comment by JoshuaLai** [comment]
@andersonvieiragomeslopes so just to be clear this isn't an issue when you run `sh iOSFramework.sh` but your own script? 

There is a mistake in your lipo command you don't specify the `.framework` it probably should look something like this:
```
lipo -create ./ios-arm64/AzureCommunicationCalling.framework/AzureCommunicationCalling ./ios-x86_64-simulator/AzureCommunicationCalling.framework/AzureCommunicationCalling -output "${YOUR_OUTPUTFOLDER_HERE}/AzureCommunicationCalling.framework/AzureCommunicationCalling"
```
Notice the input needs the `AzureCommunicationCalling` within the framework.

**Comment by emlynmac** [comment]
Just for completeness, here are the steps I took to get the app running:

My steps to get it working (Xcode 14, M1 Mac)
1. Get / update Visual Studio for Mac to latest (17.3.7, build 11)
2. In the `XamariniOSBindings/ProxyLibs/CommunicationUI-Proxy` directory, ran: `sh iOSFramework.sh`
3. Opened `CommunicationCallingXamarinSampleApp.sln` with Visual Studio
4. Built the `CommunicationUIProxy.Binding` target
5. Built and ran the `CommunicationCallingXamarinSampleApp.iOS` target with simulator.

**Comment by andersonvieiragomeslopes** [comment]
@JoshuaLai I have the same problem with the script itself or iOSFramework.sh I always get this response in the terminal.

`fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't map input file: ios-arm64/AzureCommunicationCalling.framework (Invalid argument)`
`Invalid argument`

**Comment by andersonvieiragomeslopes** [comment]
@emlynmac Well, I don't know which step I'm doing wrong, I also tried to do it that way, of course, I ran the pod install and everything worked fine, the problem is now in the final step.

**Comment by JoshuaLai** [comment]
Yes the invalid argument makes sense you shouldn't be running `lipo` on the `.framework` it should be the document inside the framework. 
`lipo -create ./ios-arm64/AzureCommunicationCalling.framework/AzureCommunicationCalling ./ios-x86_64-simulator/AzureCommunicationCalling.framework/AzureCommunicationCalling -output "${YOUR_OUTPUTFOLDER_HERE}/AzureCommunicationCalling.framework/AzureCommunicationCalling"` 
Something like this.

**Comment by andersonvieiragomeslopes** [comment]
Well, I understand the step where I went wrong when running the script, thanks for the help @emlynmac  and @JoshuaLai .
But I have a question, where are the architecture fat files needed to bind in the CommunicationUIProxy.Binding project structure or another project I want to create?

![image](https://user-images.githubusercontent.com/26186056/195691373-2a568741-51f2-40c9-9022-71dc3b85fec8.png)

**Comment by JoshuaLai** [comment]
Hi @andersonvieiragomeslopes 
The fat files can be found in the `CommunicationUI-Proxy/Framework/{debug or release}-universal`
And everything should already be hooked up in the bindings solution so there should be no action needed. 
If you are no longer having trouble with the scripts I am going to close this git issue. Feel free to reach out if more help is needed!
