### ISSUE TITLE
MAUI examples

### ISSUE THREAD

**Issue by vovanb** [Azure-Samples/communication-services-ui-library-xamarin#19]
Is it possible to port xamarin example to MAUI? Xamarin is no longer suopported.

**Comment by JoshuaLai** [comment]
Hi @vovanb, currently, we don't have official MAUI support, but we are beginning investigations on how to bring this capability over. Feel free to create an idea here: https://feedback.azure.com/d365community/forum/81ff6d2b-0c25-ec11-b6e6-000d3a4f0858 or vote for existing ones.

**Comment by JoshuaLai** [comment]
cc @garchiro7

**Comment by JoshuaLai** [comment]
I will be closing this since the investigations are beginning for MAUI support. 
Please let us know if you have any more questions or concerns. Thanks!

**Comment by JoshuaLai** [comment]
Hi @vovanb 
Following up on this suggestion. We have just recently release a similar MAUI sample in a repo here: https://github.com/Azure-Samples/communication-services-ui-library-maui
Check it out and gives us your thoughts.
