### ISSUE TITLE
MAUI support

### ISSUE THREAD

**Issue by vmgolubev** [Azure-Samples/communication-services-ui-library-xamarin#22]
Hi,
Are there any plans to add MAUI support this year?
Thanks!

**Comment by JoshuaLai** [comment]
Hi @vmgolubev , currently, we don't have official MAUI support. 
We have started looking into this. 
Feel free to create an idea or here: https://feedback.azure.com/d365community/forum/81ff6d2b-0c25-ec11-b6e6-000d3a4f0858 or vote for existing ones.

**Comment by JoshuaLai** [comment]
Hi @vmgolubev 
Following up on this suggestion. We have just recently release a similar MAUI sample in a repo here: https://github.com/Azure-Samples/communication-services-ui-library-maui
Check it out and gives us your thoughts.
