### ISSUE TITLE
How to hang up a call programmatically?

### ISSUE THREAD

**Issue by AlexJTS** [Azure-Samples/communication-services-ui-library-xamarin#23]
Hi @JoshuaLai

I'd like to know if there are a feature about Hang up on a call by method on interface or static void.
I'm trying debug CallCompositeActivity's elements like button feature hang up call but it seems not possible. Any way?

**Comment by JoshuaLai** [comment]
Hi @AlexJTS. Thanks for the question. 

Just want to understand your scenario a little bit more. You want to programatically hang up a call without the need for tapping the Leave Call button? 
Is the idea you want to hang up the call for all participants in the call? Or just for the one specific participant (as if they tapped the Leave Call button themselves)

**Comment by JoshuaLai** [comment]
cc @iaulakh @garchiro7

**Comment by AlexJTS** [comment]
Thanks for the answer, @JoshuaLai 

In that case I need a method to hang up the call of a particular participant without pressing the leave call button. For example, I am trying to set a timer for a meeting session. When the timer reaches 0 seconds, I want the application to hang up automatically. I also trying stop call by dispose activity by following code but I know its no suitable.

`Device.StartTimer(TimeSpan.FromMilliseconds(1000), () =>
            {
                do
                {
                    _countSeconds--;
                    if (_countSeconds== 0)
                    {
                        StopSession();
                        return false;
                    }
                    else
                    {
                        return true;
                    }
                } while (_countSeconds > 0);
            });
            private async void StopSession()
            {
                await ACServices.RemoveTokenUser(userIdentity);
                var currentContext = Android.App.Application.Context;
                currentContext.Dispose();
            }
            `

**Comment by JoshuaLai** [comment]
I see. I understand your workflow. For the time being we don't provide any APIs to hang up the calling like this unfortunately. I'm not sure if we have had any asks for this feature @garchiro7 can confirm. 
We would first need to expose an API in our underlying native UI composites for the Xamarin binding to call to. 
You can provide feedback here and we can have it added to our backlog. https://feedback.azure.com/d365community/forum/81ff6d2b-0c25-ec11-b6e6-000d3a4f0858

**Comment by garchiro7** [comment]
Hi, @AlexJTS I encourage you to open feedback here:  https://feedback.azure.com/d365community/forum/81ff6d2b-0c25-ec11-b6e6-000d3a4f0858,  We will add this to the backlog and continue with the effort to provide the tools that you need. 

Currently as @JoshuaLai mentioned, we don't offer the capability in the UI Library, one alternative is creating your own implementation (fork the UI Library and bubble up the functionality from the Calling SDK); since the UI Library is opensource, you can expand the current functionality 👍

**Comment by AlexJTS** [comment]
@JoshuaLai @garchiro7 Hi. Oh ok I get it, I'm very grateful by your answering. 
I have post on feedback of Azure. It would be great to add these features on manage meeting calls.

**Comment by JoshuaLai** [comment]
Thanks for the feedback! If there are any more questions or feedback please feel free to reach out to us. 
I will be closing this issue. Please feel free to reopen if there are new or other concerns.
