### ISSUE TITLE
Nuget package for xamarin

### ISSUE THREAD

**Issue by andersonvieiragomeslopes** [Azure-Samples/communication-services-ui-library-xamarin#7]
The work becomes a little more difficult as we have to assemble the package and then generate the nuget for use in the project, this could be left to microsoft, since honestly, that's what it does with the uwp package , for example.

In my opinion it could be a xamarin package and not xamarin forms, I think java/swift connections using c# should be under our responsibility, but building the library is not.

https://www.nuget.org/packages/Azure.Communication.Calling/1.0.0-beta.32

**Comment by garchiro7** [comment]
Hi @andersonvieiragomeslopes , thank you for your valuable feedback. This is an exciting opportunity for the team to bring the Xamarin bindings alternative, we are working to bring the best experience to all the developers, and we are doing research across the teams to create the NuGet package and deliver the integration. This was our initial effort to unblock Xamarin development, so keep an eye here for future releases.

 You can start using these bindings and drop any extra feedback, we will be more than happy to hear more from the Xamarin developer community.

**Comment by andersonvieiragomeslopes** [comment]
Hello @garchiro7 .

Thanks for your answer, I appreciate this initiative from microsoft, [here in this repository](https://github.com/Laerdal/Xamarin.AzureCommunicationCalling) the work is similar, of course, it's about the approach with full customization, different from this approach with the UI out of the box, it suits different use cases, but I'm happy to see microsoft efforts around xamarin with ACS.

**Comment by JoshuaLai** [comment]
Closing this issue since it has been answered. 
@andersonvieiragomeslopes please reach out if you have more questions.
