### ISSUE TITLE
[iOS] Xamarin Sample does not work with Xcode 14

### ISSUE THREAD

**Issue by JoshuaLai** [Azure-Samples/communication-services-ui-library-xamarin#9]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Build iOS sample 

### Any log messages given by the failure
> 

### Expected/desired behavior
> Should run properly 

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful
Known issue: https://github.com/xamarin/xamarin-macios/issues/15954

**Comment by emlynmac** [comment]
This is fixed in the latestVisual Studio 
Tested on 17.3.7 build 11, using M1 Mac and Xcode 14.0.1
